version: "3.8"
services:
  node:
    container_name: my-node-app
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
      
  react:
    container_name: my-react-app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"

  mysql:
    container_name: mysqldb
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - type: volume
        source: storage
        target: /var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  storage: